### ISSUE TITLE
batch_ingest_service intelligence 

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#111]
This service should inspect the directory its processing to check if there is a hyrax-migrator Work related to the BAG already in process.

**Comment by lsat12357** [comment]
The BagIngestService currently checks if a given pid is already persisted in Hyrax and skips the bag if this is the case; otherwise a MigrateWorkService will eventually be created, which checks for the existence of a migrator work before creating a new one.
