### ISSUE TITLE
Update crosswalk of Primary Sets to Admin Sets

### ISSUE THREAD

**Issue by wickr** [OregonDigital/hyrax-migrator#115]
A few new UO Admin Sets were designated: JSMA, SCUA, OAC, OHS, UO (Jordan Schnitzer Museum of Art, Special Collections and University Archives, Oregon Arts Commission, Oregon Historical Society, University of Oregon)

**Comment by jsimic** [comment]
UO Admins Sets are documented on the MAP -> Admin Sets tab

**Comment by lsat12357** [comment]
Can we have descriptions for these?

**Comment by jsimic** [comment]
Edited admin_sets_info.yml to include descriptions of all UO Admin Sets identified.

**Comment by lsat12357** [comment]
joel-palmer is mapped to 2 admin sets, ok if I map it just to uo-scua?

**Comment by lsat12357** [comment]
waiting to hear back on jsma question

**Comment by jsimic** [comment]
JSMA renamed to uo-jsma, NCU to nwcu in MAP

**Comment by raybrarian** [comment]
@jsimic - @wickr is off OD2 working on local issues at the moment. Are you available to QA this one?

**Comment by jsimic** [comment]
@raybrarian I will need to work with Linda and/or Greg

**Comment by luisgreg99** [comment]
@raybrarian @jsimic I'll work on this one next. It looks like the PR OD2#164 from @lsat12357 got merged to master, so it should now be ready for testing on staging. I'll do another migration run on staging to check the update.

**Comment by luisgreg99** [comment]
QA pass! I did a small batch of Dan_Powell_photographs on staging and they got successfully migrated to `uo-scua` admin set https://staging.oregondigital.org/admin/admin_sets/uo-scua?locale=en
