### ISSUE TITLE
BAG generation for migrating works

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#116]
Bag should be generated with a checksum encoding to match what is stored in Fedora with Hyrax. Evaluate what is provided by default in Hyrax/Fedora and make sure our OD1 bag export provides a matching checksum for the files.

**Comment by lsat12357** [comment]
so @wickr just checked and we have checksum disabled in OD1
irb(main):008:0> item.content.profile
=> {"dsLabel"=>"File Datastream", "dsVersionID"=>"content.0", "dsCreateDate"=>2015-08-02 03:55:12 UTC, "dsState"=>"A", "dsMIME"=>"image/tiff", "dsFormatURI"=>nil, "dsControlGroup"=>"M", "dsSize"=>6554548, "dsVersionable"=>true, "dsInfoType"=>nil, "dsLocation"=>"oregondigital:df70cv67g+content+content.0", "dsLocationType"=>"INTERNAL_ID", "dsChecksumType"=>"DISABLED", "dsChecksum"=>"none"}

**Comment by lsat12357** [comment]
Greg added checksums of the content file to the profiler task on OD1
https://github.com/OregonDigital/oregondigital/blob/master/lib/tasks/create_profiles.rake
and then verifies them after migration
https://github.com/OregonDigital/hyrax-migrator/blob/master/app/services/hyrax/migrator/services/verify_checksums_service.rb
