### ISSUE TITLE
migrator actor stack configuration

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#139]
Currently the actor stack is defined in lib/hyrax/migrator/middleware/configuration.rb
but it _looks_ like it's configurable in the hyrax-migrator config on the OD2 repo. Configuring it there has no effect, so this is kind of confusing. We should probably remove that from the config file, and then at some point consider making it so that middleware is configured from the migrator config file.

**Comment by lsat12357** [comment]
It is possible to do a custom stack on the fly from https://github.com/OregonDigital/hyrax-migrator/pull/153

**Comment by raybrarian** [comment]
Assigned to Greg for QA

**Comment by luisgreg99** [comment]
QA pass

I did a migration test locally and this update didn't cause any issues.
