### ISSUE TITLE
Net ReadTimeout error 

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/hyrax-migrator#148]
`Net::ReadTimeout` is raised every time the index gets updated during ingest and creates a delay:
```
server_1           | Fetching https://w3id.org/spar/mediatype/application/xml from the authorative source. (this is slow)
server_1           | Unable to fetch https://w3id.org/spar/mediatype/application/xml from the authorative source.
server_1           | Net::ReadTimeout
```

**Comment by wickr** [comment]
https://w3id.org/spar/mediatype/... redirects to sparontologies.net, which was down as of last week. It looks to be back up now, http://www.sparontologies.net/mediatype/application/xml.html is loading for me, so this should be resolved.

**Comment by raybrarian** [comment]
QA pass
