### ISSUE TITLE
modify stack so that the contents field is not passed to hyrax.

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#157]
We are currently migrating the field :contents
it is used in cpds, and the values are the uris of the children.
the uris are currently for OD1
    http://oregondigital.org/resource/oregondigital:abcde1234
We could, during the crosswalk change this to the new uri 
    https://oregondigital.org/concern/images/abcde1234.
But it seems like it would make much more sense to store only the pid.  

If we want to use this field to help generate a contents list on the show pages, it might be helpful if we also stash the model, eg. "images/abcde1234" 
To do this in migration, we'd have to look at the migrator work for each child.

**Comment by lsat12357** [comment]
wickr says contents not needed in od2 beyond using it to create the relationships.

**Comment by lsat12357** [comment]
ok, so similar to what Greg did with admin sets, access the graph directly to get at the contents triple (if it exists) in the list_children_service. Then add contents to the crosswalk_overrides and use the nil function.

**Comment by luisgreg99** [comment]
QA pass!

I did a test on staging with `df70sk17p` (complex object) and it got persisted successfully.
