### ISSUE TITLE
set config values on environment variables

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/hyrax-migrator#160]
- `skip_field_mode`
- `crosswalk_overrides_file`

**Comment by lsat12357** [comment]
this is great! and instead of setting config.ingest_local_path and config.file_system_path directly, set the environment variables for those too

**Comment by lsat12357** [comment]
Since we're trying to do an end run around the Hyrax::Migrator.config, I did the changes in the OD2 config file.
