### ISSUE TITLE
add exists? check to persist_work_service

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#170]
We've found that it is possible for the persist_work_service to have a failed status while the work actually did persist in Hyrax. The main cause for this case seems to be a failure of the file attach job, but there may be others.
If we restart the migrator stack, the middleware will try to restart from the failure point, which would mean the persist_work_service will try to run again, which we probably don't want? To fix this scenario, add a preemptive check for exists? and return success if appropriate, otherwise continue.  This will fix the status and allow the migrator stack to continue.

**Comment by lsat12357** [comment]
It is worrying that we are updating the status to success even though potentially there are problems with the work, but perhaps the way to catch and fix these will be with the validation process.

**Comment by lsat12357** [comment]
adding the exists? output as part of the error message being saved (see #179) ,  but for now, continue to allow the stack to stop so that the error can be examined.
add an exists? check before the actor starts the service, so that upon restarting the stack, the stack can continue?

**Comment by lsat12357** [comment]
For QA, open a migrator work on something that has successfully migrated
w = Hyrax::Migrator::Work.find_by(pid: pid)
change the following:
 aasm_state: 'persist_work_failed'
status_message 'work failed to persist'
status 'failed'
rerun the migration
m = Hyrax::Migrator::Middleware.default
m.start w
the Hyrax Actor stack should not be invoked.

**Comment by wickr** [comment]
QA pass.

Ran the migration, it resumed after the PersistWorkActor.

```
irb(main):014:0> m.start w
D, [2020-11-09T19:35:52.043691 #11583] DEBUG -- :   Load LDP (17.5ms) http://fcrepo.default.svc.cluster.local:8080/fcrepo/rest/prod/df/70/bm/34/df70bm349 Service: 47005082848920
D, [2020-11-09T19:35:52.216821 #11583] DEBUG -- :    (1.1ms)  BEGIN
D, [2020-11-09T19:35:52.219986 #11583] DEBUG -- :   Hyrax::Migrator::Work Update (1.9ms)  UPDATE "hyrax_migrator_works" SET "aasm_state" = $1, "status_message" = $2, "status" = $3, "updated_at" = $4 WHERE "hyrax_migrator_works"."id" = $5  [["aasm_state", "persist_work_succeeded"], ["status_message", "Work df70bm349 published to the repository."], ["status", "success"], ["updated_at", "2020-11-09 19:35:52.217244"], ["id", 1214]]
D, [2020-11-09T19:35:52.225365 #11583] DEBUG -- :    (1.6ms)  COMMIT
D, [2020-11-09T19:35:52.231591 #11583] DEBUG -- :    (0.6ms)  BEGIN
D, [2020-11-09T19:35:52.237083 #11583] DEBUG -- :   Hyrax::Migrator::Work Update (0.6ms)  UPDATE "hyrax_migrator_works" SET "aasm_state" = $1, "status_message" = $2, "updated_at" = $3 WHERE "hyrax_migrator_works"."id" = $4  [["aasm_state", "add_relationships_succeeded"], ["status_message", "Work df70bm349 No relationships to add."], ["updated_at", "2020-11-09 19:35:52.232106"], ["id", 1214]]
D, [2020-11-09T19:35:52.240270 #11583] DEBUG -- :    (1.1ms)  COMMIT
D, [2020-11-09T19:35:52.241214 #11583] DEBUG -- :    (0.2ms)  BEGIN
D, [2020-11-09T19:35:52.242632 #11583] DEBUG -- :   Hyrax::Migrator::Work Update (0.5ms)  UPDATE "hyrax_migrator_works" SET "aasm_state" = $1, "status_message" = $2, "status" = $3, "updated_at" = $4 WHERE "hyrax_migrator_works"."id" = $5  [["aasm_state", "workflow_metadata_initial"], ["status_message", nil], ["status", nil], ["updated_at", "2020-11-09 19:35:52.241501"], ["id", 1214]]
...
```
