### ISSUE TITLE
verification of metadata

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#174]
In OD1, rake task to iterate through a list of pids (possibly a batch) and generate a report of each asset containing all fields with values. To be run at time of export and included in bag.

Possibly add an actor/service to compare this file to contents in fields on OD2 during verification stage.

**Comment by lsat12357** [comment]
will require before pushing to OD2
adding config.fields_map = "config/initializers/migrator/fields_map.yml" to OD2/config/initializers/hyrax_migrator.rb
and the fields_map.yml to config/initializers/migrator/

**Comment by lsat12357** [comment]
Current usage:
obtain a profile from OD1, place in directory on container or include in work bag data
v = Hyrax::Migrator::Services::VerifyMetadataService.new(work, Hyrax::Migrator.config, profile_dir)
errors = v.verify_metadata

**Comment by luisgreg99** [comment]
`VerifyMetadataService` worked nicely on my local test!
```
work = Hyrax::Migrator::Work.find_by_pid("df66ts94x")
v = Hyrax::Migrator::Services::VerifyMetadataService.new(work, Hyrax::Migrator.config, '/data/tmp/profiles/Gerald_W_Williams_Collection')
> errors = v.verify_metadata
> ["Unable to verify rightsHolder in df66ts94x.",
 "Unable to verify localCollectionName in df66ts94x.",
 "Unable to verify format in df66ts94x.",
 "Unable to verify isPartOf in df66ts94x.",
 "Unable to verify created in df66ts94x.",
 "Unable to verify modified in df66ts94x."]
```

**Comment by luisgreg99** [comment]
QA pass!

Test on staging:
```
pid = "df70sk17p"
work = Hyrax::Migrator::Work.find_by_pid(pid)
v = Hyrax::Migrator::Services::VerifyMetadataService.new(work, Hyrax::Migrator.config, '/data/tmp/profiles')
errors = v.verify_metadata
=> ["Unable to verify od_content in df70sk17p.", "Unable to verify od_content in df70sk17p.", "Unable to verify accessionNumber in df70sk17p.", "Unable to verify rightsHolder in df70sk17p.", "Unable to verify created in df70sk17p."]
```
