### ISSUE TITLE
Date uploaded conversion from mm/dd/yyyy to EDTF

### ISSUE THREAD

**Issue by CGillen** [OregonDigital/hyrax-migrator#194]
While running a reindex of OD2 staging data, we uncovered that works coming from OD1 have the `date_uploaded` field stored as `mm/dd/yyy` where OD2 is expecting EDTF.

Can we convert `date_uploaded` from `mm/dd/yyyy` to EDTF during migration?
@wickr may have more to say and may want to do more or less with this ticket after metadata and migration team meetings.

Related: https://github.com/OregonDigital/OD2/issues/1097

**Comment by CGillen** [comment]
Update to this ticket: OD2 is expecting `#date_uploaded` to return a DateTime object from the ActiveFedora object, not EDTF formatted string

**Comment by lsat12357** [comment]
for QA, deleted and reingested an asset that uses the field date_submitted: fx71b2700

after ingest, brought up the record and tested the date_uploaded field;
irb(main):027:0> work.date_uploaded
=> Wed, 15 Apr 2020 16:41:17 +0000
irb(main):028:0> work.date_uploaded.to_datetime
=> Wed, 15 Apr 2020 16:41:17 +0000
irb(main):029:0> work.date_uploaded.is_a? DateTime
=> true
