### ISSUE TITLE
compound objects data structure

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#20]
@wickr and @lsat12357 to pair up and translate the OD1 compound object structure to something that will work in OD2.

A compound object maps to these types of notions;
- A book with multiple pages
- A scanned image with its article

These might work as a parent => child, or even a child having multiple parent works. 

During migration having the ability to make the translation prior to creating the work.

**Comment by lsat12357** [comment]
We are able to migrate compound objects; using the contents property, the add_relationships_service populates a given parent's work_members_attributes and hands off to the Hyrax stack.update.
