### ISSUE TITLE
actor/service should check access restrictions term and read_groups agree

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#208]
if either read_groups is not public and/or there is a value set for access_restrictions, that these agree. otherwise, the migration should fail; this check could either happen in the visibility actor/service or a new set can be added.

**Comment by lsat12357** [comment]
could also add this to the preflight tools.

**Comment by lsat12357** [comment]
Greg is adding this code to the preflight tools. see https://github.com/OregonDigital/oregondigital/pull/1360

**Comment by luisgreg99** [comment]
QA PAss.

https://github.com/OregonDigital/oregondigital/pull/1360 is now in place in OD1. I did a test preflight check with one asset in Texts and Data collection (known to have UO restricted content) and didn't show any additional issues when running preflight.rake.
