### ISSUE TITLE
report number of cpds and restricted items

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#216]
for QA purposes, metadata team would like these numbers added to the epic ticket. It was suggested this be collected at preflight; it would make more sense to collect when we do the export and create profiles.

**Comment by luisgreg99** [comment]
QA Pass

Exported Oregon Hops And Brewing Archives (seed data) collection and got the reporting info in the `exportlogs` folder as expected:

```
$ cat /data1/batch/exports/exportlogs/export_Oregon_Hops_And_Brewing_Archives_seed_data_2020-08-07-220346.log
# Logfile created on 2020-08-07 15:03:46 -0700 by logger.rb/1.2.8
I, [2020-08-07T15:04:01.538392 #54253]  INFO -- : Number of CPDs: 0
I, [2020-08-07T15:04:01.538662 #54253]  INFO -- : Number of restricted items: 0
```
