### ISSUE TITLE
profile and verification of cpd parent

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#226]
Currently the create_profile task is printing out the value of od_content the way it is with all other properties, which is a problem, because od_content is an array of assets. to fix, add a method similar to set and primarySet.
After migration, to include contents (i.e. the list of children) in the verification service, there would also need to be a separate method added as this property is not mapped to anything in OD2.

**Comment by lsat12357** [comment]
separating this into two tickets. This ticket addresses the changes to the create_profile task, see #231 for the verification bit.

**Comment by lsat12357** [comment]
for QA, running the profile task on a cpd should print a profile with the children's ids listed.

**Comment by wickr** [comment]
QA pass, child pids listed in children, not as objects in descMetadata
