### ISSUE TITLE
add a verification service for cpds

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#231]
if an asset is a compound object, verify that all the children are attached. Adding list of children in the profile.

**Comment by lsat12357** [comment]
for QA:
  find an asset on staging that is a cpd
  delete one of the children
  run verification on the parent
    w = Hyrax;:Migrator::Work.find_by(pid: pid)
    vs = Hyrax::Migrator::Services::VerificationService.new(w, Hyrax::Migrator.config)
    errors = vs.verify
errors should report the missing child

**Comment by lsat12357** [comment]
turns out if you delete a child, it doesn't entirely disappear from the ordered_members_ids, but becomes nil, therefore the ordered_members_ids.size remains the same.

**Comment by wickr** [comment]
QA pass
Deleted child work on staging. Ran verification service. Error logged with child pid.
```
irb(main):003:0> errors = vs.verify
=> [[], [], [], ["df708k016 missing;"]]
```
