### ISSUE TITLE
use jobs to handle verification

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#239]
since verification for a given work has become a little involved, thinking forward to when we will be scaling up.  model the process on the batch ingest process. this will add:
batch verification service to iterate through all the pids in a batch and launch one job per work
the verify work job, which launches a service
the verify work service which launches the verification service on the work, receives back any errors and adds them to the work.env.
Then the batch reporter can be used to find out if any errors were flagged.
The verify work service could have been the verification service, and may still be combined, but for a few factors:
 - the verification service requires the config, which currently can't be passed through the job so the verify work service just uses the default config
 - the verification service calls all the verification classes and returns the results; the verify work service writes them into the work env.

**Comment by lsat12357** [comment]
Also, at one time we thought about including the verification stuff in the migration stack, but it's unclear that this would work, mainly because of the multiple jobs that are launched for a given work.

**Comment by lsat12357** [comment]
how will errors be handled, given sidekiq is automatically going to retry the job.
the verification should handle any errors and flag them in the work or log if it is something that needs to be fixed, eg one of the profiles is missing.

**Comment by lsat12357** [comment]
will need to modify the OD2 hyrax migrator config to stash the list of verify services when the gem is updated on OD2

**Comment by lsat12357** [comment]
QA
to use:
b = Hyrax::Migrator::Services::BatchVerificationService.new('batchname')
b.verify
##should result in any verification errors being added to each migrator work, eg
work.env[:verification_errors] = [["Unable to verify format in fx719n361.", "Unable to verify extent in fx719n361.", "Unable to verify dateDigitized in fx719n361.", "Unable to verify imageResolution in fx719n361.", "Unable to verify colorSpace in fx719n361."], [],[],[]]

can also be used with a specific set of verifiers, eg VerifyMetadataService only
b = Hyrax::Migrator::Services::BatchVerificationService.new('batchname', {verify_services:['Hyrax::Migrator::Services::VerifyMetadataService']})
b.verify

**Comment by wickr** [comment]
QA pass
Jobs were launched to verify works:
```ruby
irb(main):006:3* b = Hyrax::Migrator::Services::BatchVerificationService.new(batchname, {verify_services: ['Hyrax::Migrator::Services::VerifyMetadataService', '
Hyrax::Migrator::Services::VerifyVisibilityService', 'Hyrax::Migrator::Services::VerifyChecksumsService', 'Hyrax::Migrator::Services::VerifyChildrenService',
irb(main):007:0>       'Hyrax::Migrator::Services::VerifyDerivativesService']} )
=> #<Hyrax::Migrator::Services::BatchVerificationService:0x0000559040148040 @batch_name="gifford", @options={:verify_services=>["Hyrax::Migrator::Services:...
irb(main):008:0> b.verify
I, [2021-06-02T11:31:50.092582 #2248]  INFO -- : [ActiveJob] Enqueued Hyrax::Migrator::Jobs::VerifyWorkJob (Job ID: 74c8bc46-773c-45fa-bcc5-7b2a9e106b8d) to Sidekiq(hyrax_migrator) with arguments: {:verify_services=>["Hyrax::Migrator::Services::VerifyMetadataService", "Hyrax::Migrator::Services::VerifyVisibilityService", "Hyrax::Migrator::Services::VerifyChecksumsService", "Hyrax::Migrator::Services::VerifyChildrenService", "Hyrax::Migrator::Services::VerifyDerivativesService"], :pid=>"s7526c681"}
I, [2021-06-02T11:31:50.094176 #2248]  INFO -- : [ActiveJob] Enqueued Hyrax::Migrator::Jobs::VerifyWorkJob (Job ID: b7ad8682-0a13-4812-bfee-ffc41fa1efbc) to Sidekiq(hyrax_migrator) with arguments: {:verify_services=>["Hyrax::Migrator::Services::VerifyMetadataService", "Hyrax::Migrator::Services::VerifyVisibilityService", "Hyrax::Migrator::Services::VerifyChecksumsService", "Hyrax::Migrator::Services::VerifyChildrenService", "Hyrax::Migrator::Services::VerifyDerivativesService"], :pid=>"ng451h841"}
I, [2021-06-02T11:31:50.095729 #2248]  INFO -- : [ActiveJob] Enqueued Hyrax::Migrator::Jobs::VerifyWorkJob (Job ID: 2d72ac8f-f242-4c1d-8401-d53e39e21877) to Sidekiq(hyrax_migrator) with arguments: {:verify_services=>["Hyrax::Migrator::Services::VerifyMetadataService", "Hyrax::Migrator::Services::VerifyVisibilityService", "Hyrax::Migrator::Services::VerifyChecksumsService", "Hyrax::Migrator::Services::VerifyChildrenService", "Hyrax::Migrator::Services::VerifyDerivativesService"], :pid=>"dn39x182m"}
...
```
