### ISSUE TITLE
file checksums

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#267]
we might be overdoing it with the checksums/validation
1. checksum taken on the datastream before it is exported
2. checksum taken as part of bag creation
3. bag is validated
4. during file upload, checksum taken, compared with bag manifest
5. hyrax does a checksum
6. post-migration checksum from step 1 compared with hyrax checksum

Possibly eliminate bag validation which takes 24.46 seconds
  after the export, the only changes to the bag are to zip the contents and then unzip them. We could possibly wait to zip the bag until after it is migrated, and keep it short term, until verification is completed.
Possibly eliminate checksum during file upload

**Comment by lsat12357** [comment]
see also #268

**Comment by lsat12357** [comment]
for QA, migrate an asset, should successfully complete.

**Comment by wickr** [comment]
QA pass
Linda's 500 works of doris-ulmann_aa successfully migrated
