### ISSUE TITLE
modify batch reporter

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#277]
because the new batch verification service ultimately stashes any errors in the migrator work, modify the batch reporter to enable a verification report

**Comment by lsat12357** [comment]
to QA
after the batch verification has run ( so that there are results to be had)
b = Hyrax::Migrator::Services::BatchReporter.new('batchname', {data_list: [:verification]})
b.write_report
OR
b.screen_report

**Comment by wickr** [comment]
QA pass
Reporter writes screen report and also saves file: gifford_report_20210602183614.txt
```verification
s7526c681: [["Unable to verify photographer in s7526c681.", "Unable to verify rights in s7526c681.", "Unable to verify rightsHolder in s7526c681.", "Unable to verify license in s7526c681.", "Unable to verify format in s7526c681.", "Unable to verify modified in s7526c681."], "", [], [], []]
ng451h841: [["Unable to verify photographer in ng451h841.", "Unable to verify rights in ng451h841.", "Unable to verify rightsHolder in ng451h841.", "Unable to verify license in ng451h841.", "Unable to verify format in ng451h841.", "Unable to verify modified in ng451h841."], "", [], [], []]
```
