### ISSUE TITLE
metadata verification failing rights_statement and license

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#288]
the verifier is basing a comparison between od1 and od2 values with respect to the od2 map; rights_statement and license are both expected to be single values but are represented as arrays in od2, causing the fail even though the actual content is correct.
if od2 behavior is not changeable, the comparison will need to ignore the presence of arrays and test for the correct values.

**Comment by lsat12357** [comment]
this can be a config change in crosswalk_overrides.

**Comment by lsat12357** [comment]
for QA run verification on something with rights
batchname = 
b = Hyrax::Migrator::Services::BatchVerificationService.new(batchname)
b.verify
b = Hyrax::Migrator::Services::BatchReporterService.new(batchname, {data_list:[:verification]})
b.screen_report

**Comment by wickr** [comment]
QA pass.
Verification report showed no failing messages.
```
Printing verification for batch minorities-lgbtq-barometer *****************************
df71wz36t: [[], "", [], [], []]
fx71cs676: [[], "", [], [], []]
df71wz54r: [[], "", [], [], []]
fx71cs722: [[], "", [], [], []]
df71wz569: [[], "", [], [], []]
```
