### ISSUE TITLE
Collection / AdminSet membership service

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#30]
## Descriptive summary

A new work needs to be associated to an adminset (and possibly multiple collections). 

A configuration for each Work Type could point at a Service that is responsible for parsing the metadata to identify the appropriate AdminSet and Collection(s). The Service can be written (and overridden) to meet our specific OD2 needs but allow for anyone downstream to tailor the memberships to their own needs.

**Comment by revgum** [comment]
- Associate work to AdminSet using crosswalk logic:
  - OD "Primary Set" -> AdminSet
  - or fallback to "Repository" or "Institution" metadata -> AdminSet
- Generate some sort of crosswalk to associate OD set (collection) -> Collection(s)
- OD "Primary Set" -> Specific Collection (specific collection type) (used for OAI)

**Comment by lsat12357** [comment]
![screenshot from 2019-02-13 10-15-06](https://user-images.githubusercontent.com/7526686/52733787-72327080-2f78-11e9-9cf5-2128ab37e820.png)
