### ISSUE TITLE
display profiles

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#309]
as a way to build confidence and/or expose problems in the migration workflow, add views of the asset profiles.

**Comment by lsat12357** [comment]
QA by going to 
staging.oregondigital.org/migrator/batches/clarence-andrews
(or any batch id)
and then clicking on one of the assets listed
for checking on children, uo-veterans is good (profiles are good)

**Comment by wickr** [comment]
QA Pass.
![image](https://user-images.githubusercontent.com/2293544/140538042-0ae05f5f-933c-46b2-8d63-89c62ad3781e.png)
