### ISSUE TITLE
hack for adding full_size_download_allowed

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#324]
This is to address the problem of how to populate full_size_download_allowed, which is not on OD1 but is on OD2:
set is ignored by the CrosswalkMetadataService because mapping and adding the collection is handled by a different actor/service.
We can therefore hack set on the crosswalk_overrides.yml

property: full_size_download_allowed
predicate: http://opaquenamespace.org/ns/set
multiple: false
function: populate_fullsize

and then add to the CrosswalkMetadataService
populate_fullsize(object)
  //something like if default-true-colls.include? object.to_s ? true : false
end
also needs a yml file with colls mapped to true/false
a function that builds a list of all the default true colls or vice-versa, whichever is smaller

**Comment by lsat12357** [comment]
this is going to be slightly tricky...if we are basing the map on set considering OSU assets with multiple sets.  so possibly it needs to be on primary set, with set as a fallback. While these functions appear to only have access to the object value from the statement being processed, we can certainly get the graph and pull out what we need

**Comment by jsimic** [comment]
There is a [permissions grid](https://docs.google.com/spreadsheets/d/1i3oMHsADViBjh5b_uM6qLi63K1ZwIeraZQgzhKYJEhc/edit#gid=0)

**Comment by lsat12357** [comment]
QA see asset df70wx94c, will probably need to look at it in the console in order to see the field.

**Comment by wickr** [comment]
QA pass
ChinaVine asset is marked as true
```ruby
irb(main):004:0> item = Video.find('df70wx94c')
D, [2022-06-16T10:30:29.760172 #66640] DEBUG -- :   Load LDP (44.9ms) http://fcrepo.od2-test.svc.cluster.local:8080/fcrepo/rest/prod/df/70/wx/94/df70wx94c Service: 513020
=> #<Video id: "df70wx94c", head: [#<ActiveTriples::Resource:0x7d9ec ID:<http://fcrepo.od2-test.svc.cluster.local:8080/fcrepo/rest/prod/df/70/wx/94/df70wx9...
irb(main):006:0> item.full_size_download_allowed
=> true
```
alice b. sheldon asset marked as false
```ruby
irb(main):015:0> item2 = Document.find('df724p268')
D, [2022-06-16T10:53:32.667961 #66640] DEBUG -- :   Load LDP (43.1ms) http://fcrepo.od2-test.svc.cluster.local:8080/fcrepo/rest/prod/df/72/4p/26/df724p268 Service: 513020
=> #<Document id: "df724p268", head: [#<ActiveTriples::Resource:0x7e48c ID:<http://fcrepo.od2-test.svc.cluster.local:8080/fcrepo/rest/prod/df/72/4p/26/df724p268/list_source#g787160>>]...
irb(main):016:0> item2.full_size_download_allowed
=> false
```
