### ISSUE TITLE
chinavine multiple institutions breaks admin set service

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#330]
the exciting combination of no primary set plus multiple institutions is not handled by the admin set service.
for example, see https://oregondigital.org/sets/chinavine/oregondigital:df70wx94c

**Comment by lsat12357** [comment]
the admin set service starts with trying to map to an admin set with primary set and as a fallback, uses institution. it is more common for there to be multiple sets than it is for there to be multiple insitutions. If there isn't a case where an asset with multiple institutions doesn't include either uo or osu as one of them, we could look for those.

**Comment by jsimic** [comment]
Everything UO publishes should have UO as an institution at a minimum

**Comment by lsat12357** [comment]
For QA: I will migrate a couple of chinavine assets that have multiple institutions.  The admin set should be set to uo
