### ISSUE TITLE
Check workflow metadata for destroyed status before migrating

### ISSUE THREAD

**Issue by wickr** [OregonDigital/hyrax-migrator#39]
OD1 has a "soft delete" feature which hides items in the interface but doesn't actually remove them from the repository. At this point we don't have a reason to migrate them, but they may be exported. 

The migrator needs to check workflowMetadata.yml  very early for `destroyed: true` and if so, reject the work.

**Comment by lsat12357** [comment]
per our migration meeting, we're going to shoot for omitting destroyed works from the migration pid lists, and then add a second check to the preflight rake task. It will not be run as part of the official migration stack.

**Comment by lsat12357** [comment]
this is a destroyed asset: oregondigital:df66jj57z

**Comment by luisgreg99** [comment]
QA pass:

```
$ cat test-asset-status.txt
oregondigital:df66jj57z

$ RAILS_ENV=production bundle exec rake preflight_tools:preflight work_dir=tmp/preflight-test-2 pidlist=test-asset-status.txt

$ cat tmp/preflight-test-2/report_20200619151736.txt
Working on oregondigital:df66jj57z...
status: destroyed
```
