### ISSUE TITLE
Service that takes uploaded list of pids and queues a job for each one

### ISSUE THREAD

**Issue by lsat12357** [OregonDigital/hyrax-migrator#6]

**Comment by revgum** [comment]
This functionality should be abstracted into a service, or something, that takes the list of pids and starts the background job for each migration. This notion will make it possible for a controller or a rake task to start the same migration process.

**Comment by revgum** [comment]
The service would have some awareness of how to find the zip file for each pid (be it on the local filesystem or an S3 bucket)
