### ISSUE TITLE
license metadata invalid and mismapped?

### ISSUE THREAD

**Issue by revgum** [OregonDigital/hyrax-migrator#70]
The test bag has metadata that is being mapped to `license`, it seems like it should be `rights_statement`. 

Also, the value here isn't a valid license or rights_statement in OD2. 

```
<http://oregondigital.org/resource/oregondigital:3t945r08v> <http://purl.org/dc/terms/rights> <http://opaquenamespace.org/ns/rights/rr-f> .
```

**Comment by vantuyls** [comment]
@jsimic @carakey @wickr

**Comment by wickr** [comment]
There is still work planned to clean up Rights values in OD1, in Workcycle 5.

**Comment by revgum** [comment]
If necessary, we are also able to configure a function in the crosswalk to perform a lookup/translation from opaquenamespace to rights urls

**Comment by lsat12357** [comment]
Mapping has been fixed and the metadata remediated.
